name: CI
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pnpkm
        uses: ianwalter/puppeteer@3.0.0
        with:
          args: npm i -g pnpm
      - name: Install
        uses: ianwalter/puppeteer@3.0.0
        with:
          args: pnpm i
      - name: Lint
        uses: ianwalter/puppeteer@3.0.0
        with:
          args: pnpm lint
      - name: Test
        uses: ianwalter/puppeteer@3.0.0
        with:
          args: pnpm t
