name: CI
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ianwalter/puppeteer:v4.0.0
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pnpm
        run: npm i -g pnpm
      - name: Install
        run: pnpm i
      - name: Lint
        run: pnpm lint
      - name: Test
        run: pnpm t
